name: vim
base: core18
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: vim
description: |
  Snappy the official Vim

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  vim:
    # See 'snapcraft plugins'
    source: .
    plugin: make
    #configflags: [-DCMAKE_INSTALL_PREFIX=/]
    build-packages:
      - libncurses5-dev
      - libncursesw5-dev
    
apps:
  vim:
    command: usr/local/bin/vim
   
