name: vim-editor
base: core18
version: '8.2.788' # just for humans, typically '1.2+git' or '1.3.2'
summary: vim
description: |
  Snappy the official Vim

grade: stable 
confinement: strict 

parts:
  vim-editor:
    source: .
    plugin: make
    build-packages:
      - libncurses5-dev
      - libncursesw5-dev
    
apps:
  vim-editor:
    command: usr/local/bin/vim
   
